### ISSUE TITLE
Add default applications as AppImages

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nitrux-legacy-bug-tracker#3]
To further fit within our scope of providing a system that focuses on portable applications we need to include the default applications packaged in the AppImage format. These are:

KDE Apps:
- Ark
- Babe
- Calamares**
- Dolphin
- Info Center
- Kate
- Konsole
- Ksysguard
- Spectacle
- Systemsettings (including Nomad Firewall)

3rd party apps:
- Chromium
- <del>Kvantum
- <del>Latte
- ONLYOFFICE Desktop Editors*
- VLC
- qpdfview
- ShowImage

Nomad apps:
- Software Center

----
The only exception here is going to be ONLYOFFICE and that's because we'd have to talk to them in order to get them to release the software as an AppImage since their code isn't open source.

For the theming to work in all the apps probably we'd need that each AppImage includes Kvantum in them.

**Comment by azubieta** [comment]
The applications below have an strong dependence on KF5 and plasma, so i think that in order to don't have copies of the same libs all over the place we could keep them as part of the base system.
    Ark
    Dolphin
    Info Center
    Kate
    Konsole
    Ksysguard
    Spectacle
    Systemsettings (including Nomad Firewall)

**Comment by UriHerrera** [comment]
Got it. So we cut the list to these apps:

3rd party apps:
- Chromium
- Kvantum
- Latte
- VLC
- qpdfview
- ShowImage
